### ISSUE TITLE
inbound_routing scale

### ISSUE THREAD

**Issue by budgrise** [sonic-net/DASH#233]
I have some questions about the inbound_routing table.
This is basically a follow-on to https://github.com/Azure/DASH/pull/194

1) Can we double check that eni_id is a key field to the inbound_routing table?
The documentation below refers only to the VNI and the SIP prefix:
https://github.com/Azure/DASH/blob/main/documentation/general/dash-sonic-hld.md#22-inbound-packet-processing-pipeline

(I believe that multiple ENIs can be in the same VNET, and thus use the same VNI.
If so, then the inbound routing table needs to have a duplicate entry for each such ENI.
In the worst case, all 64 ENIs could be in the same VNET, requiring many duplicated entries.)

2) I’m trying to understand the sizing requirements for the inbound_routing table.
There are a couple parts here and I’m not sure how they all fit in.

I recall a meeting where it was stated that the pa_validation table has the same scale as the mapping table –
10 million entries. Is the inbound_routing table the same scale? 

It was stated in https://github.com/Azure/DASH/pull/194 that the SIP key of the inbound_routing table
was definitely ternary, not lpm.  Are we required to support millions of TCAM entries for this table?

It was also stated in the doc that the SIP prefix is optional, and is needed to differentiate between vnets
that happen to have the same VNI. How often does this happen? In other words, how many inbound_routing
table entries are expected to specify a SIP prefix? Is it mostly all of the entries, hardly any, not known, etc.  

When a SIP prefix is specified for an VNI, is it typically used to distinguish between two vnets? 
Or between a small number of vent, or an unlimited number of vnets?

**Comment by chrispsommers** [comment]
Hi @prsunny and @marian-pritsak this is a blocker to develop tests for vnet_in. For some initial tests, the scale issues which @budgrise raised are less important than the functional issues @anton7811 raised in https://github.com/Azure/DASH/issues/233#issuecomment-1256213992. Any help would be welcome.

**Comment by prsunny** [comment]
Inbound routing rules can be a maximum of 1k, but, on an average, it would be around ~100.

**Comment by aputriax** [comment]
@marian-pritsak I've created a branch for testing this issue. Here is [**the link**](https://github.com/reshmaintel/DASH/tree/inbound_routing_issue_verification). It includes all necessary changes from the Chris's branch. Use [standard procedure](https://github.com/Azure/DASH/tree/main/dash-pipeline#i-feel-lucky) to run the tests. But instead of `make run-all-tests` do the following:
```
make run-saithrift-client-bash
cd ptf
./run-saithrift-ptftests.sh saidasheni
```
So far all tests should pass. By default inbound routing entry is commented out.


Now uncomment [line 52](https://github.com/reshmaintel/DASH/blob/59ce25029bf4c8626bbb41aa2155ed924f10315c/dash-pipeline/tests/saithrift/ptf/func/saidasheni.py#L52) and run specifically create-delete test:
```
./run-saithrift-ptftests.sh saidasheni.CreateDeleteEniTest
``` 

In the switch tab you'll see the error I mentioned:
```
[04:57:51.621] [bmv2] [E] [thread 17] [P4Runtime] Invalid match type
```

Additionally you can run one more test to verify the fix - scale test. Uncomment lines 887-890 and run:
```
./run-saithrift-ptftests.sh saidasheni.EniScaleTest
```

**NOTE**: If possible, please take a look at get attributes and delete tests (lines 57-64).

**Comment by yusefMS06** [comment]
Seems that queries were answered on the thread. 
Can we close issue? @prsunny @marian-pritsak @budgrise

**Comment by budgrise** [comment]
It's ok by me to close this issue.

**Comment by yusefMS06** [comment]
Closing

**Comment by chrispsommers** [comment]
Hi, There is still a failure during bmv2 testing. This bug is unresolved. The PTF test is skipped (for example, see https://github.com/sonic-net/DASH/blob/aff7eae183b500f73ac2cd46d5b7a97e591c6db8/test/test-cases/functional/ptf/saidasheni.py#L56) and we will have to skip it during some SAI-Challenger DASH API tests we're writing for draft PR https://github.com/sonic-net/DASH/pull/301

**Comment by mgheorghe** [comment]
any update on this ?

**Comment by yusefMS06** [comment]
Let's consider closing based on first and moving second part to its own issue. 
@anton7811
