### ISSUE TITLE
Ixia controller security risk (TLS 1.1 enabled)

### ISSUE THREAD

**Issue by Pterosaur** [sonic-net/DASH#357]
Some test cases depend on the Ixia controller(CONTROLLER_VERSION=0.0.1-3587) platform as the traffic generator which is deployed at: 
https://github.com/sonic-net/DASH/blob/7dd0ba0085e54a623a141efe8cb4d9d19c3a9b34/test/third-party/traffic_gen/deploy_ixiac.sh#L4

But the controller service support TLS 1.0 and TLS1.1 which are unsafe to downgrade attacks since they rely on SHA-1 hash for the integrity of exchanged messages.

We should upgrade the controller or disable the TLS 1.0 and 1.1 support in this controller.

![image](https://user-images.githubusercontent.com/18609639/228858945-a2ef172e-0b4e-4da2-9b8a-5efbb22ad3bd.png)

**Comment by chrispsommers** [comment]
@Pterosaur This controller is used for CI/CD testing in the test pipeline, in a very controlled environment. Why is this deemed a security risk? It is not a production component. I will investigate your claims but I don't see how this is a "risk."

**Comment by lguohan** [comment]
@chrispsommers , unfortunately we are treating test environment the same way as production, so it is a secuirty risk for us. we can not run it till TLS 1.0 AND 1.1 are disabled.

**Comment by Pterosaur** [comment]
We can check whether a service support TLS 1.1 by the command `openssl s_client -connect 127.0.0.1:443 -tls1_2 -cipher DEFAULT@SECLEVEL=1`

**Comment by Pterosaur** [comment]
The issue version we are using is 0.0.1-3587. But I tried some controllers with newer versions from(https://github.com/orgs/open-traffic-generator/packages/container/package/ixia-c-controller) that cannot pass all test cases of DASH. I guess the interfaces has been modified.

**Comment by chrispsommers** [comment]
Hi @Pterosaur, the controller and traffic engines are released as a compatible set, so you can't just upgrade one and get a predictable result. AFAIK all controllers have same issue. We are treating it seriously and will address it ASAP.

Depending upon which commit of DASH you used, you might have picked up a version which had a CI failure due to a sequence of MRs which caused a regression, since fixed in https://github.com/sonic-net/DASH/pull/355. If the failures you saw look similar to https://github.com/sonic-net/DASH/actions/runs/4555886865/jobs/8036577440#step:22:1394 this would explain it. If not, perhaps it was the controller/traffic-engine pairing.

**Comment by chrispsommers** [comment]
New version of ixia-c resolves this issue https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-4064, I will upgrade the DASH test infra to use it soon.
