### ISSUE TITLE
Sai attributes for ACL rules should include list of IP prefixes for the Bmv2 compile

### ISSUE THREAD

**Issue by vincent-xs** [sonic-net/DASH#360]
SAI API /attribute generation is based on the BMV2 compile.
currently, for ACL rule, dst_ip_addr and src_ip_addr are generated as IP addresses, when they should be a list of IP prefixes.

this should be enabled using DASH_MATCH in dash_acl.p4 as default for the Bmv2 model for it is the base compile used by vendors to generate the SAI api.

**Comment by KrisNey-MSFT** [comment]
Following up for @vincent-xs 

The current P4 code has a mismatch between the BMv2 and the SAI generation. To SAI, it’s list of prefixes, But to BMv2, it’s just a single prefix. This reason of difference is due to the limitation of BMv2 that cannot support the list of prefix as the key.
We totally agree with using DASH_MATCH in dash_acl.p4 as default so that other vendors don’t need to declare DASH_MATCH in their pipeline.

                So, here are two solutions to achieve our goal.

1.	To set DASH_MATCH as default, but to remove this MACRO in BMv2 pipeline. This solution is simple enough but isn’t perfect because the gap between BMv2 and SAI still exists.

2.	And another solution, (possibly better) comes from @lguohan .  We should keep the same declaration of list prefixes in P4 code. Although BMv2 doesn’t support list prefixes, we can expand the list of prefixes in saiapi level and input the single prefix to BMv2 one by one. This solution will be a little bit complicated but more reasonable.

**Comment by kcudnik** [comment]
btw. just to clarify, i'm not the person which will work on this to make this happen, since i don't have knowledge about p4 and bmv2 and their limitation, i'm just waiting to sai headers dash match sai repo headers

**Comment by KrisNey-MSFT** [comment]
all matching except for list-match-type

**Comment by r12f** [comment]
I believe this is done by #486.

**Comment by r12f** [comment]
@KrisNey-MSFT , we should be able to have this issue closed now.

**Comment by KrisNey-MSFT** [comment]
Closing per Community Call

**Comment by kcudnik** [comment]
Is this fixed ?

**Comment by KrisNey-MSFT** [comment]
@r12f indicated it is covered by #486
