### ISSUE TITLE
SAI Meta out of libsai

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#395]
Per June 21 2023 DASH Community Call.

Should we compile SAI Meta into SAI Thrift?  This is super old, not sure how to answer how it goes together.  There might be missing symbols.  SAI Meta out of libsai would be the Issue - K to create & assign (Marian, Chris, Vijay, K~)

**Comment by KrisNey-MSFT** [comment]
@vijasrin to further articulate details of the ask

**Comment by mukeshmv** [comment]
Ask is to be able to run DASH SAI thrift tests on the same vendor SAI library that is used in the SONiC production system with SONiC syncd. 
The problem is that DASH SAI thrift server fails to build unless the vendor SAI library is linked with the SAI meta since we run into undefined reference for the following symbol otherwise: sai_metadata_get_attr_metadata.

However, in the case of production system, the SONiC syncd links the libsaimetadata, so there is no need for the vendor SAI library to include the SAI meta objects again. This makes sense since the SAI meta info is generated based on the SAI API definition and hence constant across all vendors, so it does not belong in the vendor SAI library.

**Comment by chrispsommers** [comment]
I'll take a look!

**Comment by chrispsommers** [comment]
I made a temporary branch of DASH here: https://github.com/chrispsommers/DASH/tree/no-saimeta-in-libsai. This removes sai-meta from bmv2 libsai, but a problem remains.

If you `make clean && make all` you get unresolved symbol errors while building saithrift-server. This might be an oversight in the saithrift-server build recipe itself. It assumes that the vendor libsai contains saimeta utils, which is why DASH bmv2 libsai had code to build certain files, e.g. see https://github.com/sonic-net/DASH/blob/64cbb0ae83f65b14469f8554ace942ca18c3a8d1/dash-pipeline/SAI/templates/Makefile.j2#L5 and related compile instructions. (I'd arrived at all this empirically long ago, without questioning the SAI saithrift-server build process.)

So, with this modified branch, sai-meta code is not compiled into bmv2 libsai. If you do the following:
```
make clean && make all
```
it will build p4 code, build sai-headers, (*not* build sai-meta anymore), build libsai - all OK up to this point - then fail to build saithrift-server during the final linkage stage, as follows:
```
g++ -L/usr/lib -Wl,-rpath=/usr/lib ./obj/sai_rpc_server.o ./obj/saiserver.o -o saiserver \
	   ./obj/librpcserver.a -lthrift -lpthread -lsai  -L/lib/x86_64-linux-gnu -Wl,-rpath=/lib/x86_64-linux-gnu -lm -L/usr/local/lib/ -Wl,-rpath=/usr/local/lib -lpthread -lpiprotogrpc -lpiprotobuf -lprotobuf -lgrpc++ -lgrpc -lpiall -lpi_dummy -lpthread -labsl_synchronization -labsl_status -labsl_raw_hash_set -lgpr -lre2 -lssl -laddress_sorting
/usr/bin/ld: ./obj/sai_rpc_server.o: in function `convert_attr_thrift_to_sai(_sai_object_type_t, sai::sai_thrift_attribute_t const&, _sai_attribute_t*)':
/dash/dash-pipeline/SAI/SAI/test/saithriftv2/../../meta/sai_rpc_frontend.cpp:132: undefined reference to `sai_metadata_get_attr_metadata'
/usr/bin/ld: ./obj/sai_rpc_server.o: in function `convert_attr_sai_to_thrift(_sai_object_type_t, _sai_attribute_t const&, sai::sai_thrift_attribute_t&)':
/dash/dash-pipeline/SAI/SAI/test/saithriftv2/../../meta/sai_rpc_frontend.cpp:554: undefined reference to `sai_metadata_get_attr_metadata'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:103: saiserver] Error 1
make[2]: Leaving directory '/dash/dash-pipeline/SAI/SAI/test/saithriftv2'
make[1]: *** [Makefile:46: saithrift-build] Error 2
make[1]: Leaving directory '/dash/dash-pipeline/SAI/SAI'
make: *** [Makefile:44: saithrift-server] Error 2
make: *** [Makefile:233: saithrift-server] Error 2
```
It seems like the https://github.com/opencomputeproject/SAI/blob/master/test/saithriftv2/Makefile ought to be compiling the sai-meta files instead of relying upon vendor libsai to contain them. @reshmaintel do you think you could have someone look into this? @mukeshmv or @vijasrin feel free to experiment as well, perhaps try modifying the above [Makefile](https://github.com/opencomputeproject/SAI/blob/master/test/saithriftv2/Makefile) to compile meta into the saithrift server would be a good approach.

**Comment by KrisNey-MSFT** [comment]
Possibly remove from production libsai?  It would live in SAI Thrift Server build?  
Per notes from Community Call 7/12/2023
@reshmaintel and team to take a look

**Comment by mukeshmv** [comment]
I saw some reference to include sai meta in saithrift server but only if it is for a VS platform build. 
https://github.com/opencomputeproject/SAI/blob/master/test/saithrift/Makefile#L44
I am not sure what it means.

**Comment by chrispsommers** [comment]
@mukeshmv Once saithrift-server is built, the generated code contains 125 references to `convert_attr_sai_to_thrift`, see below. You won't see it in SAI source code per se, it's generated on the fly by the Perl scripts in the saithrift-server make process.
```
grep -rn --include=*.cpp convert_attr_sai_to_thrift
SAI/SAI/meta/sai_rpc_server.cpp:67:    convert_attr_sai_to_thrift(static_cast<sai_object_type_t>(SAI_OBJECT_TYPE_ACL_COUNTER), attr_list[i], attribute);
SAI/SAI/meta/sai_rpc_server.cpp:97:    convert_attr_sai_to_thrift(static_cast<sai_object_type_t>(SAI_OBJECT_TYPE_ACL_ENTRY), attr_list[i], attribute);
SAI/SAI/meta/sai_rpc_server.cpp:127:    convert_attr_sai_to_thrift(static_cast<sai_object_type_t>(SAI_OBJECT_TYPE_ACL_RANGE), attr_list[i], attribute);

...etc....
```
Count occurrences:
```
grep -rn --include=*.cpp convert_attr_sai_to_thrift|wc
    125     500   19456
```

**Comment by chrispsommers** [comment]
Capturing a synopsis I'd communicated in side-channels as an aid to understanding this issue:

o	Saithrift server requires that vendor libsai contains some code from sai-meta (in particular, convert_attr_sai_to_thrift() seems to be the culprit)
o	Vendors prefer not to include this code in libsai since it’s only for saithrift test harnesses, not production, so it’s a burden
o	DASH saithrift incudes sai-meta because experimentally I discovered that without sai-meta, saithrift server won’t build (final linkage error, missing references as shown)
o	The task is to modify saithrift server to compile and link in sai-meta as part of building the sairpc server, so that vendor libsai doesn’t have to. Oner proof that this works would be a successful build of DASH saithrift server when saimeta is omitted from DASH libsai build.
o	There might be collateral impacts on project already building saithrift server – if those projects indeed build sai-meta into vendor libsai, will there be duplicate symbols in the final linkage of sairpc server, or will it ignore them?
o	I might be overlooking something in the above, it’s possible I could be building DASH libsai or saithrift server differently to avoid this problem. If so, there may be a simpler solution.

**Comment by kcudnik** [comment]
Same issue related here: https://github.com/opencomputeproject/SAI/pull/1825

**Comment by KrisNey-MSFT** [comment]
Hope is to move code to SAI Thrift server itself, if anyone wants to take a look

**Comment by kcudnik** [comment]
saimetadata is not getting out from sonic/orchagent/syncd, it's main core in there and thats the main reason metadata was created, i will create libsaimetadata.so library next to saithrift server, and compile next to libsai.so in DASH, but it still would be beneficial to use metadata inside libsai.so as project will grow. so actual other vendors would not need to compile metadata into theirown libsai.so is they wish to, but will have to redistribute libsaimetadata.so with saithrif server anyway

**Comment by KrisNey-MSFT** [comment]
@kcudnik - is it ok to close this Issue as Done?

**Comment by kcudnik** [comment]
> @kcudnik - is it ok to close this Issue as Done?

im still working on this

**Comment by kcudnik** [comment]
this brings up step closer https://github.com/opencomputeproject/SAI/pull/1901, some changes will need to be done i libsai i dash repo to finish this

**Comment by KrisNey-MSFT** [comment]
Already merged SAI Repo & DASH
Can start using metadata in libsai
Closing
