### ISSUE TITLE
Update the latest DASH SAI to OCP repo

### ISSUE THREAD

**Issue by Pterosaur** [sonic-net/DASH#579]
@r12f 
When will we sync the latest DASH SAI, including HA part, to OCP SAI repo?

**Comment by r12f** [comment]
Since the DASH is an ongoing effort, this ask is very vague. (It is hard to define the "latest" : D)

Ze, is there any specific API that you need is missing or any commit ID that you are looking at?

In DASH, usually whoever submits the change needs to take the API to OCP SAI. So, is anything is missing, feel free to reach out to the owner (PR submitters) to get them merged into OCP SAI.

If you are looking for some changes that is not merged or created yet, it will not be actionable. And please refer to our internal project planning and tracking to see the progress.

**Comment by Pterosaur** [comment]
Thanks for your suggestion and I will send the request to you in the internal channel.
